# Generated by Django 6.0.6 on 2026-06-15 18:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Кличка')),
                ('age_months', models.PositiveIntegerField(default=0, verbose_name='Возраст (мес.)')),
                ('status', models.CharField(choices=[('available', 'Свободен'), ('reserved', 'Забронирован'), ('adopted', 'Пристроен')], default='available', max_length=20, verbose_name='Статус')),
                ('is_active', models.BooleanField(default=True, verbose_name='Опубликован')),
                ('arrived_at', models.DateField(auto_now_add=True, verbose_name='Дата поступления')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pets', to='core.category', verbose_name='Категория')),
                ('curator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='curated_pets', to='staff.specialist', verbose_name='Куратор')),
            ],
            options={
                'verbose_name': 'Питомец',
                'verbose_name_plural': 'Питомцы',
                'ordering': ['-arrived_at'],
            },
        ),
        migrations.CreateModel(
            name='MedicalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnosis', models.CharField(max_length=255, verbose_name='Диагноз / процедура')),
                ('notes', models.TextField(blank=True, verbose_name='Заметки')),
                ('is_vaccinated', models.BooleanField(default=False, verbose_name='Вакцинирован')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Дата записи')),
                ('vet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medical_records', to='staff.specialist', verbose_name='Ветеринар')),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_records', to='pets.pet', verbose_name='Питомец')),
            ],
            options={
                'verbose_name': 'Медицинская запись',
                'verbose_name_plural': 'Медицинские карты',
                'ordering': ['-created_at'],
            },
        ),
    ]
