# Generated by Django 6.0.6 on 2026-06-17 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0002_pet_breed_pet_description_pet_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pet',
            options={'ordering': ['-arrived_at', '-id'], 'verbose_name': 'Питомец', 'verbose_name_plural': 'Питомцы'},
        ),
    ]
