# Generated by Django 6.0.6 on 2026-06-15 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Specialist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='ФИО')),
                ('role', models.CharField(choices=[('vet', 'Ветеринар'), ('curator', 'Куратор'), ('volunteer', 'Волонтёр')], default='vet', max_length=20, verbose_name='Должность')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='Телефон')),
                ('is_active', models.BooleanField(default=True, verbose_name='Работает')),
                ('categories', models.ManyToManyField(blank=True, related_name='specialists', to='core.category', verbose_name='Работает с категориями')),
            ],
            options={
                'verbose_name': 'Специалист',
                'verbose_name_plural': 'Специалисты',
                'ordering': ['full_name'],
            },
        ),
    ]
