# Generated by Django 6.0.6 on 2026-06-17 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialist',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='staff/', verbose_name='Фото'),
        ),
    ]
